name: 'my_new_project'
version: '1.0.0'
config-version: 2
profile: 'default'

models:
  my_new_project:
    mart:
      +materialized: table
      finance:
        +schema: finance
    intermediate:
      +materialized: view 
    staging:
      +materialized: view