version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: "Ham verilerin bulunduğu ana kaynak"
    tables:
      - name: product
        identifier: raw_gz_product
        description: "Greenweez ürün listesi"
        columns: 
          - name: products_id
            description: "Birincil anahtar (Ürünün benzersiz kimliği)"
            tests:
              - unique
              - not_null
          - name: purchSE_PRICE
            description: "Ürünün satın alma fiyatı (maliyet)"
            tests: 
              - not_null

      - name: sales
        identifier: raw_gz_sales
        description: "Greenweez satış verileri / Her siparişteki her ürün için bir satır bulunur"
        columns:
          - name: date_date
            description: "Satın Alma Tarihi"
          - name: orders_id || '-' || pdt_id
            description: "Birincil Anahtar"
            tests:
              - not_null
              - unique
          - name: orders_id
            description: "Sipariş kimliği (Teslimat tablosuyla bağlantı kurar)"
            tests:
              - not_null
          - name: pdt_id
            description: "Ürün kimliği (Ürün tablosuyla bağlantı kurar)"
            tests:
              - not_null
          - name: revenue
            description: "Müşterinin ödediği tutar. Ciro = Miktar * Satış Fiyatı"
            tests:
              - not_null
          - name: quantity
            description: "Verilen siparişte satın alınan ürün adedi"
            tests:
              - not_null
          - name: date_date
            description: "Satın alma tarihi"
            tests:
              - not_null

      - name: ship
        identifier: raw_gz_ship
        description: "Greenweez siparişlerine ait nakliye ve teslimat verileri"
        columns:
          - name: orders_id
            description: "Birincil anahtar (Sipariş kimliği)"
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: "Müşterinin nakliye için ödediği ücret"
            tests:
              - not_null
          - name: logCost
            description: "Dağıtım merkezinde/depoda paketin hazırlanma maliyeti"
            tests:
              - not_null
          - name: ship_cost
            description: "Greenweez'in lojistik firmasına ödediği nakliye maliyeti"
            tests:
              - not_null
      
      - name: adwords
        identifier: raw_gz_adwords
        description: "Google ADS kampanya performans verileri"
        data_tests:
          - dbt_utils.unique_combination_of_columns:
              arguments:
                combination_of_columns:
                  - date_date
                  - campaign_key
                  - camPGN_name
        columns:
          - name: date_date
            description: "Kampanya Tarihi"
            tests:
              - not_null
          - name: paid_source
            description: "Reklam Kaynağı"
            tests:
              - not_null
          - name: campaign_key
            description: "Kampanya Kodu"
            tests:
              - not_null
          - name: camPGN_name
            description: "Kampanya Adı"
            tests:
              - not_null
          - name: ads_cost
            description: "Reklam Maliyeti"
          - name: impression
            description: "Reklam Gösterim Sayısı"
          - name: click
            description: "Reklam Tıklanma Sayısı"

      - name: bing
        identifier: raw_gz_bing
        description: "BİNG kampanya performans verileri"
        data_tests:
          - dbt_utils.unique_combination_of_columns:
              arguments:
                combination_of_columns:
                  - date_date
                  - campaign_key
                  - camPGN_name
        columns:
          - name: date_date
            description: "Kampanya Tarihi"
            tests:
              - not_null
          - name: paid_source
            description: "Reklam Kaynağı"
            tests:
              - not_null
          - name: campaign_key
            description: "Kampanya Kodu"
            tests:
              - not_null
          - name: camPGN_name
            description: "Kampanya Adı"
            tests:
              - not_null
          - name: ads_cost
            description: "Reklam Maliyeti"
          - name: impression
            description: "Reklam Gösterim Sayısı"
          - name: click
            description: "Reklam Tıklanma Sayısı"

      - name: criteo
        identifier: raw_gz_criteo
        description: "CRİTEO kampanya performans verileri"
        data_tests:
          - dbt_utils.unique_combination_of_columns:
              arguments:
                combination_of_columns:
                  - date_date
                  - campaign_key
                  - camPGN_name
        columns:
          - name: date_date
            description: "Kampanya Tarihi"
            tests:
              - not_null
          - name: paid_source
            description: "Reklam Kaynağı"
            tests:
              - not_null
          - name: campaign_key
            description: "Kampanya Kodu"
            tests:
              - not_null
          - name: camPGN_name
            description: "Kampanya Adı"
            tests:
              - not_null
          - name: ads_cost
            description: "Reklam Maliyeti"
          - name: impression
            description: "Reklam Gösterim Sayısı"
          - name: click
            description: "Reklam Tıklanma Sayısı"

      - name: facebook
        identifier: raw_gz_facebook
        description: "FACEBOOK kampanya performans verileri"
        data_tests:
          - dbt_utils.unique_combination_of_columns:
              arguments:
                combination_of_columns:
                  - date_date
                  - campaign_key
                  - camPGN_name
        columns:
          - name: date_date
            description: "Kampanya Tarihi"
            tests:
              - not_null
          - name: paid_source
            description: "Reklam Kaynağı"
            tests:
              - not_null
          - name: campaign_key
            description: "Kampanya Kodu"
            tests:
              - not_null
          - name: camPGN_name
            description: "Kampanya Adı"
            tests:
              - not_null
          - name: ads_cost
            description: "Reklam Maliyeti"
          - name: impression
            description: "Reklam Gösterim Sayısı"
          - name: click
            description: "Reklam Tıklanma Sayısı"

      - name: campaigns
        identifier: int_campaigns
        description: "Tüm kampanya performans verileriE"
        data_tests:
          - dbt_utils.unique_combination_of_columns:
              arguments:
                combination_of_columns:
                  - date_date
                  - campaign_key
                  - camPGN_name
        columns:
          - name: date_date
            description: "Kampanya Tarihi"
            tests:
              - not_null
          - name: paid_source
            description: "Reklam Kaynağı"
            tests:
              - not_null
          - name: campaign_key
            description: "Kampanya Kodu"
            tests:
              - not_null
          - name: camPGN_name
            description: "Kampanya Adı"
            tests:
              - not_null
          - name: ads_cost
            description: "Reklam Maliyeti"
            tests:
              - not_null
          - name: impression
            description: "Reklam Gösterim Sayısı"
            tests:
              - not_null
          - name: click
            description: "Reklam Tıklanma Sayısı"
            tests:
              - not_null

      